### ISSUE TITLE
Theme on Chrome 81 doesn't change the address bar colour to dark

### ISSUE THREAD

**Issue by nanopulga** [Fiddle-N/material-deep-black-theme#2]
Since Chrome 81, the theme doesn't change the adress bar colour because there were some changes in Chrome, or at least this Reddit thread talks about itit https://www.reddit.com/r/chrome/comments/fdwuny/themes_suddenly_dont_keep_the_dark_address_bar/ I really liked this theme and I would be really happy if it got updated so the address bar could go back to be black again. Thank you.

**Comment by Fiddle-N** [comment]
Fixed :) You may either wait for the update to hit, or manually uninstall and reinstall the theme [here](https://chrome.google.com/webstore/detail/material-deep-black-theme/kicomekdnoaegbahblnaiccfbcnhbfhb) if you wish to install it right away.
